# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-datadog-notify
  description: Github Action for https://github.com/dvmtn/datadog-notify, which sends an event api call to Datadog
  homepage: https://cloudposse.com/accelerate
  topics: ""
